package com.demo.entities;// default package
// Generated Jan 27, 2025, 4:56:06 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;



/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "jobs")
public class Answer implements java.io.Serializable {

	private Integer id;
	private Question question;
	private String content;
	private Boolean isCorrect;

	public Answer() {
	}

	public Answer(Question question, String content) {
		this.question = question;
		this.content = content;
	}

	public Answer(Question question, String content, Boolean isCorrect) {
		this.question = question;
		this.content = content;
		this.isCorrect = isCorrect;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questionID", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "is_correct")
	public Boolean getIsCorrect() {
		return this.isCorrect;
	}

	public void setIsCorrect(Boolean isCorrect) {
		this.isCorrect = isCorrect;
	}

}
