package com.demo.entities;// default package
// Generated Jan 27, 2025, 4:56:06 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "jobs")
public class Question implements java.io.Serializable {

	private Integer id;
	private Test test;
	private int questionType;
	private String content;
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Question() {
	}

	public Question(Test test, int questionType, String content) {
		this.test = test;
		this.questionType = questionType;
		this.content = content;
	}

	public Question(Test test, int questionType, String content, Set<Answer> answers) {
		this.test = test;
		this.questionType = questionType;
		this.content = content;
		this.answers = answers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testID", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@Column(name = "question_type", nullable = false)
	public int getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(int questionType) {
		this.questionType = questionType;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
