package com.demo.entities;
// Generated Nov 3, 2024, 6:35:19 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name = "employer", catalog = "jobs")
public class Employer implements java.io.Serializable {

	private int id;
	private User user;
	private String companyName;
	private String companyProfile;
	private double rating;
	private String contactInfo;
	private String logo;
	private String coverImg;
	private String address;
	private String mapLink;
	private double amount;
	private boolean status;
	private String description;
	private String foundedIn;
	private String teamMember;
	private String companyField;
	private String companyLink;

	public Employer() {
	}

	public Employer(User user, String companyName, String companyProfile, double rating, String contactInfo,
			String logo, String coverImg, String address, String mapLink, double amount, boolean status,
			String description, String foundedIn, String teamMember, String companyField, String companyLink) {
		this.user = user;
		this.companyName = companyName;
		this.companyProfile = companyProfile;
		this.rating = rating;
		this.contactInfo = contactInfo;
		this.logo = logo;
		this.coverImg = coverImg;
		this.address = address;
		this.mapLink = mapLink;
		this.amount = amount;
		this.status = status;
		this.description = description;
		this.foundedIn = foundedIn;
		this.teamMember = teamMember;
		this.companyField = companyField;
		this.companyLink = companyLink;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "company_name", nullable = false, length = 65535)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "company_profile", nullable = false, length = 65535)
	public String getCompanyProfile() {
		return this.companyProfile;
	}

	public void setCompanyProfile(String companyProfile) {
		this.companyProfile = companyProfile;
	}

	@Column(name = "rating", nullable = false, precision = 22, scale = 0)
	public double getRating() {
		return this.rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}

	@Column(name = "contact_info", nullable = false, length = 65535)
	public String getContactInfo() {
		return this.contactInfo;
	}

	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo;
	}

	@Column(name = "logo", nullable = false, length = 65535)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "cover_img", nullable = false, length = 65535)
	public String getCoverImg() {
		return this.coverImg;
	}

	public void setCoverImg(String coverImg) {
		this.coverImg = coverImg;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "map_link", nullable = false, length = 65535)
	public String getMapLink() {
		return this.mapLink;
	}

	public void setMapLink(String mapLink) {
		this.mapLink = mapLink;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "founded_in", nullable = false, length = 65535)
	public String getFoundedIn() {
		return this.foundedIn;
	}

	public void setFoundedIn(String foundedIn) {
		this.foundedIn = foundedIn;
	}

	@Column(name = "team_member", nullable = false, length = 65535)
	public String getTeamMember() {
		return this.teamMember;
	}

	public void setTeamMember(String teamMember) {
		this.teamMember = teamMember;
	}

	@Column(name = "company_field", nullable = false, length = 65535)
	public String getCompanyField() {
		return this.companyField;
	}

	public void setCompanyField(String companyField) {
		this.companyField = companyField;
	}

	@Column(name = "company_link", nullable = false, length = 65535)
	public String getCompanyLink() {
		return this.companyLink;
	}

	public void setCompanyLink(String companyLink) {
		this.companyLink = companyLink;
	}

}
