package com.demo.entities;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Membership generated by hbm2java
 */
@Entity
@Table(name = "membership", catalog = "jobs")
public class Membership implements java.io.Serializable {

	private Integer id;
	private String name;
	private double price;
	private String description;
	private String duration;
	private boolean status;
	private Integer typeFor; // Thêm cột type_for kiểu Integer
	private Set<Employermembership> employermemberships = new HashSet<Employermembership>(0);

	public Membership() {
	}

	public Membership(String name, double price, String description, String duration, boolean status, Integer typeFor) {
		this.name = name;
		this.price = price;
		this.description = description;
		this.duration = duration;
		this.status = status;
		this.typeFor = typeFor;
	}

	public Membership(String name, double price, String description, String duration, boolean status,
					  Integer typeFor, Set<Employermembership> employermemberships) {
		this.name = name;
		this.price = price;
		this.description = description;
		this.duration = duration;
		this.status = status;
		this.typeFor = typeFor;
		this.employermemberships = employermemberships;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "duration", nullable = false, length = 65535)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "type_for", nullable = false) // Thêm ánh xạ cho cột type_for
	public Integer getTypeFor() {
		return this.typeFor;
	}

	public void setTypeFor(Integer typeFor) {
		this.typeFor = typeFor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membership")
	public Set<Employermembership> getEmployermemberships() {
		return this.employermemberships;
	}

	public void setEmployermemberships(Set<Employermembership> employermemberships) {
		this.employermemberships = employermemberships;
	}
}