package com.demo.entities;// default package
// Generated Jan 27, 2025, 4:56:06 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * Interview generated by hbm2java
 */
@Entity
@Table(name = "interview", catalog = "jobs")
public class Interview implements java.io.Serializable {

	private Integer id;
	private Application application;
	private Date scheduledAt;
	private String interviewLink;
	private int status;

	public Interview() {
	}

	public Interview(Application application, Date scheduledAt, String interviewLink, int status) {
		this.application = application;
		this.scheduledAt = scheduledAt;
		this.interviewLink = interviewLink;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduled_at", nullable = false, length = 19)
	public Date getScheduledAt() {
		return this.scheduledAt;
	}

	public void setScheduledAt(Date scheduledAt) {
		this.scheduledAt = scheduledAt;
	}

	@Column(name = "interview_link", nullable = false, length = 65535)
	public String getInterviewLink() {
		return this.interviewLink;
	}

	public void setInterviewLink(String interviewLink) {
		this.interviewLink = interviewLink;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
