package com.demo.entities;
// Generated Oct 5, 2024, 2:53:07 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;
/**
 * Testhistory generated by hbm2java
 */
@Entity
@Table(name = "testhistory", catalog = "jobs")
public class Testhistory implements java.io.Serializable {

	private Integer id;
	private Test test;
	private User user;
	private Date timeSubmit;
	private int score;

	public Testhistory() {
	}

	public Testhistory(Test test, User user, Date timeSubmit, int score) {
		this.test = test;
		this.user = user;
		this.timeSubmit = timeSubmit;
		this.score = score;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testID", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeSubmit", nullable = false, length = 19)
	public Date getTimeSubmit() {
		return this.timeSubmit;
	}

	public void setTimeSubmit(Date timeSubmit) {
		this.timeSubmit = timeSubmit;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

}
