package com.demo.entities;// default package
// Generated Jan 27, 2025, 4:56:06 PM by Hibernate Tools 4.3.6.Final

import java.time.LocalDateTime;
import jakarta.persistence.*;

/**
 * Testhistory generated by hbm2java
 */
@Entity
@Table(name = "testhistory", catalog = "jobs")
public class Testhistory implements java.io.Serializable {

	private Integer id;
	private Test test;
	private User user;
	private LocalDateTime timeSubmit;
	private int score;
	private String contentAnswer;

	public Testhistory() {
	}

	public Testhistory(Test test, User user, LocalDateTime timeSubmit, int score, String contentAnswer) {
		this.test = test;
		this.user = user;
		this.timeSubmit = timeSubmit;
		this.score = score;
		this.contentAnswer = contentAnswer;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testID", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "timeSubmit", nullable = false)
	public LocalDateTime getTimeSubmit() {
		return this.timeSubmit;
	}

	public void setTimeSubmit(LocalDateTime timeSubmit) {
		this.timeSubmit = timeSubmit;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Column(name = "contentAnswer", nullable = false, length = 500)
	public String getContentAnswer() {
		return this.contentAnswer;
	}

	public void setContentAnswer(String contentAnswer) {
		this.contentAnswer = contentAnswer;
	}
}
